# Generated by Django 5.2.4 on 2025-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('blood_pressure', models.CharField(help_text='e.g. 120/80', max_length=7)),
                ('cholesterol', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
